### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/markdown-preview#163]
_From @tgwizard on December 10, 2014 21:20_

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package
### Steps To Reproduce
1. I had a markdown file in preview, side-by-side with the .md file
2. I closed the .md file, and the preview took up the entire window
3. I right-clicked the tab header for the preview and chose split right
4. Crash and this report
### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67

TypeError: Cannot read property 'destroyItem' of undefined
  at PaneView._results.push._this.(anonymous function) [as destroyItem] (/Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:48)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:89:76
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.resolveEditor (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:94:16)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.afterAttach (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:39:21)
  at callAttachHooks (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:342:67)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:111:9)
  at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:160:7)
  at atom-pane.PaneElement.initialize (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:79:41)
  at Object.createView (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:97:34)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:43:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/main.js:29:36
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:127:16
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:319:27)
  at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane.js:97:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:121:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:174:19)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app/src/pane.js:658:23)
  at Pane.module.exports.Pane.splitRight (/Applications/Atom.app/Contents/Resources/app/src/pane.js:626:19)
  at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:274:31)
  at space-pen-ul.subscriptions.add.atom.commands.add.tabs:split-right (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:87:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

_Copied from original issue: atom/atom#4523_

**Comment by 50Wliu** [comment]
Hasn't happened since.
