### ISSUE TITLE
Error when opening the preview

### ISSUE THREAD

**Issue by adrien59cadri** [atom/markdown-preview#177]
on windows 8.1, the document, is located on a distant file server

works fine with markdown pad 2

Uncaught TypeError: undefined is not a function
c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\renderer.js:145
Hide Stack Trace
TypeError: undefined is not a function
  at convertCodeBlocksToAtomEditors (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\renderer.js:145:47)
  at c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\renderer.js:41:7
  at c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\renderer.js:80:16
  at module.exports (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\roaster\lib\roaster.js:66:14)
  at render (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\renderer.js:73:12)
  at Object.exports.toDOMFragment (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\renderer.js:30:12)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdownText (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\markdown-preview-view.js:246:23)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdown (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\markdown-preview-view.js:241:21)
  at c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\markdown-preview-view.js:108:26
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.resolveEditor (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\markdown-preview-view.js:115:16)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.attached (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\markdown-preview\lib\markdown-preview-view.js:45:21)
  at space-pen-div.View.element.attached (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\pane.js:264:22)
  at Pane.module.exports.Pane.addItem (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\pane.js:327:14)
  at c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\src\workspace.js:518:16
  at _fulfilled (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:749:13)
  at c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:810:14
  at flush (c:\Users\adrien\AppData\Local\atom\app-0.174.0\resources\app\node_modules\q\q.js:108:17)
  at process._tickCallback (node.js:386:11)
The error was thrown from the markdown-preview package You can help by creating an issue. Please explain what actions triggered this error.

**Comment by benogle** [comment]
When you saw this error, was there a 'create issue' button at the bottom of it? Any reason why you copy/pasted the error rather than clicking the button?

**Comment by adrien59cadri** [comment]
No, for other issues yes but not this one

**Comment by kevinsawicki** [comment]
This seems like it might be a duplicate of https://github.com/atom/markdown-preview/issues/176

Can you try upgrading to Atom 0.176?

**Comment by adrien59cadri** [comment]
This is fixed in V0.176 thank you
