### ISSUE TITLE
Uncaught TypeError: undefined is not a function (when using HTML <pre> tag)

### ISSUE THREAD

**Issue by alanfranz** [atom/markdown-preview#179]
Write the following markdown:

```
# asd

<pre>
some preformatted text
</pre>
```

Try rendering the preview.

**Atom Version**: 0.175.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.124.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:145

TypeError: undefined is not a function
  at convertCodeBlocksToAtomEditors (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:145:47)
  at /usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:41:7
  at /usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:80:16
  at module.exports (/usr/share/atom/resources/app/node_modules/roaster/lib/roaster.js:66:14)
  at render (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:73:12)
  at Object.exports.toDOMFragment (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:30:12)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdownText (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:258:23)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdown (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:253:21)
  at /usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:200:17
  at /usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:213:22
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1151:25

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
This will be fixed in the next Atom version, 0.176.0.
