### ISSUE TITLE
Uncaught Error: Module version mismatch. Expected 41, got 17.

### ISSUE THREAD

**Issue by paulomcnally** [atom/markdown-preview#196]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.125.0

### Stack Trace

Uncaught Error: Module version mismatch. Expected 41, got 17.

```
At /Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422

Error: Module version mismatch. Expected 41, got 17.
  at Error (native)
  at Object.module.(anonymous function) [as .node] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/paulomcnally/.atom/packages/markdown-preview/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/paulomcnally/.atom/packages/markdown-preview/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/6to5.js:140:21)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/paulomcnally/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:8:10)
  at Object.<anonymous> (/Users/paulomcnally/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:74:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at isMarkdownPreviewView (/Users/paulomcnally/.atom/packages/markdown-preview/lib/main.coffee:13:26)
  at Object.module.exports.toggle (/Users/paulomcnally/.atom/packages/markdown-preview/lib/main.coffee:76:8)
  at atom-workspace.atom.commands.add.markdown-preview:toggle (/Users/paulomcnally/.atom/packages/markdown-preview/lib/main.coffee:42:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -2:31.5 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
  3x -2:29.2 click (span.name.icon.icon-file-text)
  2x -2:24.2 editor:newline (atom-text-editor.editor)
     -2:22.2 core:paste (atom-text-editor.editor)
     -2:20.8 core:move-up (atom-text-editor.editor)
     -2:20.4 editor:newline (atom-text-editor.editor)
     -2:16.5 core:save (atom-text-editor.editor)
 42x -2:01.6 click (span.name.icon.icon-file-text)
     -0:08.7 core:select-all (atom-text-editor.editor.is-focused)
     -0:08.2 core:paste (atom-text-editor.editor.is-focused)
  6x -0:07.7 core:save (atom-text-editor.editor.is-focused)
     -0:05.1 click (div.underlayer)
     -0:01.4 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:00.6 click (div.underlayer)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-compile-coffee",
      "linter"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
archive-view, v0.44.0
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
autocomplete-plus-async, v0.22.0
coffee-lint, v0.7.3
color-picker, v1.4.4
jsdoc, v0.7.0
jshint, v1.2.0
language-csharp, v0.3.0
language-cshtml, v0.1.0
language-dockerfile, v0.1.0
language-dust, v0.1.0
language-dustjs, v0.2.0
language-ejs, v0.1.0
language-jade, v0.3.0
language-nginx, v0.4.0
language-slim, v0.3.0
less-autocompile, v0.3.3
linter-jscs, v1.4.9
linter-jsonlint, v0.1.2
markdown-preview, v0.125.0
minifier, v0.2.0
omnisharp-atom, v0.1.6
pretty-json, v0.3.2
run-in-browser, v0.1.1
seti-syntax, v0.2.1
seti-ui, v0.6.1
slim-language, v2.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment]
@paulomcnally Based on the debugging information, it seems that you have `markdown-preview, v0.125.0` installed locally. Can you try removing that local copy and see if that helps?

**Comment by paulomcnally** [comment]
Solved. Thanks
