### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by spairo** [atom/markdown-preview#199]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.124.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:145

TypeError: undefined is not a function
  at convertCodeBlocksToAtomEditors (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:145:47)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:41:7
  at /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:80:16
  at module.exports (/Applications/Atom.app/Contents/Resources/app/node_modules/roaster/lib/roaster.js:66:14)
  at render (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:73:12)
  at Object.exports.toDOMFragment (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/renderer.js:30:12)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdownText (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:258:23)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.renderMarkdown (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:253:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:108:26
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.resolveEditor (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:115:16)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.attached (/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:45:21)
  at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:110:24)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:353:14)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:327:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:524:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:810:14
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
  3x -1:01.9 markdown-preview:toggle (atom-text-editor.editor.autocomplete-active)
     -0:25.4 core:paste (atom-text-editor.editor.mini)
     -0:22.9 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 markdown-preview:toggle (atom-text-editor.editor.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-angularjs",
      "atom-beautifier",
      "linter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.3
autocomplete-plus, v2.1.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Could you please try upgrading to Atom 0.179.0 and seeing if you can still reproduce this?

**Comment by 50Wliu** [comment]
Actually-please see #176 for details and upgrade Atom to resolve this issue.
