### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by JustSomeDood** [atom/markdown-preview#200]
[Enter steps to reproduce below:]

1. Install plugin manually via git clone into the package directory
2. Start Atom and hit Ctrl + Shift + M to initiate the plugin
** Ubuntu 14.04 64bit system

**Atom Version**: 0.179.0
**System**: linux 3.13.0-45-generic
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.137.0

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:353

Error: Cannot find module 'atom-space-pen-views'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/justsomedood/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:4:24)
  at Object.<anonymous> (/home/justsomedood/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript [as .coffee] (/opt/atom/resources/app/src/coffee-cache.js:74:19)
  at Module.load (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at isMarkdownPreviewView (/home/justsomedood/.atom/packages/markdown-preview/lib/main.coffee:11:26)
  at Object.module.exports.toggle (/home/justsomedood/.atom/packages/markdown-preview/lib/main.coffee:78:8)
  at atom-workspace.atom.commands.add.markdown-preview:toggle (/home/justsomedood/.atom/packages/markdown-preview/lib/main.coffee:43:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
  2x -3:55.3 window:run-package-specs (atom-text-editor.editor.mini)
     -3:50.1 command-palette:toggle (atom-text-editor.editor)
  2x -3:35.5 markdown-preview:toggle (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "markdown-preview": {}
}
```

### Installed Packages

```coffee
# User
atom-w3c-validation, v0.1.3
indent-guide-improved, v1.1.1
markdown-preview, v0.137.0

# Dev
No dev packages
```

**Comment by JustSomeDood** [comment]
Cloned the github repository and manually placed it in the .atom/packages directory.  On first run got this js error.  Checked for updates, checked other packages and even changed to the default theme just to make sure I cover my bases.

**Comment by 50Wliu** [comment]
Please do not manually install packages.  Atom handles this for you.

**Comment by JustSomeDood** [comment]
neither apm via command line nor the in built packages installer are working due to my internet.  I'll have to work around that then i guess
