### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/usr/share/atom/resources/app/node_modules/roaster/node_modules/cheerio/index.js'

### ISSUE THREAD

**Issue by drewzh** [atom/markdown-preview#203]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.178.0
**System**: linux 3.18.7-200.fc21.x86_64
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.134.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/usr/share/atom/resources/app/node_modules/roaster/node_modules/cheerio/index.js'

```
At fs.js:570

Error: ENOENT, no such file or directory '/usr/share/atom/resources/app/node_modules/roaster/node_modules/cheerio/index.js'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/usr/share/atom/resources/atom/common/lib/asar.js:329:27)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/6to5.js:136:21)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:8:13)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/renderer.js:190:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/6to5.js:138:21)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:20:14)
  at Object.<anonymous> (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:383:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/6to5.js:138:21)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at isMarkdownPreviewView (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/main.js:20:29)
  at Object.module.exports.toggle (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/main.js:112:11)
  at atom-workspace.atom.commands.add.markdown-preview:toggle (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/main.js:58:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/command-palette/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
  2x -2:12.8 editor:select-to-first-character-of-line (atom-text-editor.editor.autocomplete-active)
  2x -2:11.4 core:backspace (atom-text-editor.editor.autocomplete-active)
  3x -2:10.4 core:save (atom-text-editor.editor.autocomplete-active)
     -2:02.4 core:copy (atom-text-editor.editor)
  2x -2:01.2 core:paste (atom-text-editor.editor)
  3x -1:59.2 core:save (atom-text-editor.editor)
     -0:42.2 command-palette:toggle (atom-text-editor.editor)
     -0:37.0 core:confirm (atom-text-editor.editor.mini)
     -0:36.9 markdown-preview:toggle (atom-text-editor.editor)
     -0:04.1 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.2 core:confirm (atom-text-editor.editor.mini)
     -0:01.2 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "seti-ui",
      "seti-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-runner, v2.2.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
docblockr, v0.5.8
emmet, v2.3.3
language-docker, v1.1.2
linter, v0.11.1
linter-csslint, v0.0.11
linter-js-yaml, v0.1.3
linter-jshint, v0.1.0
linter-tidy, v0.0.1
minimap, v4.1.3
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
open-last-project, v0.2.2
seti-monokai, v0.3.1
seti-ui, v0.6.3
travis-ci-status, v0.11.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Refs atom/release-notes#29-should this be closed in favor of that issue?

**Comment by drewzh** [comment]
I should of searched! Closing...

**Comment by 50Wliu** [comment]
It was in a totally different repo so it shouldn't be your fault :wink:.
