### ISSUE TITLE
Uncaught Error: Replacing non-existent child

### ISSUE THREAD

**Issue by toloco** [atom/markdown-preview#236]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.139.0

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At /usr/share/atom/resources/app/src/pane-container.js:195

Error: Replacing non-existent child
  at PaneContainer.module.exports.PaneContainer.replaceChild (/usr/share/atom/resources/app/src/pane-container.js:195:15)
  at PaneAxis.module.exports.PaneAxis.reparentLastChild (/usr/share/atom/resources/app/src/pane-axis.js:178:19)
  at PaneAxis.module.exports.PaneAxis.removeChild (/usr/share/atom/resources/app/src/pane-axis.js:146:21)
  at /usr/share/atom/resources/app/src/pane-axis.js:186:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneAxis.module.exports.PaneAxis.destroyed (/usr/share/atom/resources/app/src/pane-axis.js:202:20)
  at PaneAxis.module.exports.Model.destroy (/usr/share/atom/resources/app/node_modules/theorist/lib/model.js:218:14)
  at PaneAxis.module.exports.PaneAxis.reparentLastChild (/usr/share/atom/resources/app/src/pane-axis.js:179:19)
  at PaneAxis.module.exports.PaneAxis.removeChild (/usr/share/atom/resources/app/src/pane-axis.js:146:21)
  at /usr/share/atom/resources/app/src/pane-axis.js:186:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.destroyed (/usr/share/atom/resources/app/src/pane.js:658:20)
  at Pane.module.exports.Model.destroy (/usr/share/atom/resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroy (/usr/share/atom/resources/app/src/pane.js:649:39)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:413:21)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:457:16)
  at PaneView._results.push._this.(anonymous function) [as destroyItem] (/usr/share/atom/resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at /usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:110:76
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.resolveEditor (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:115:16)
  at MarkdownPreviewView.module.exports.MarkdownPreviewView.attached (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/markdown-preview-view.js:45:21)
  at space-pen-div.View.element.attached (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/usr/share/atom/resources/app/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
  at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/usr/share/atom/resources/app/src/pane-container-element.js:47:14)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.setRoot (/usr/share/atom/resources/app/src/pane-container.js:187:20)
  at PaneContainer.module.exports.PaneContainer.replaceChild (/usr/share/atom/resources/app/src/pane-container.js:197:19)
  at PaneAxis.module.exports.PaneAxis.reparentLastChild (/usr/share/atom/resources/app/src/pane-axis.js:178:19)
  at PaneAxis.module.exports.PaneAxis.removeChild (/usr/share/atom/resources/app/src/pane-axis.js:146:21)
  at /usr/share/atom/resources/app/src/pane-axis.js:186:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.destroyed (/usr/share/atom/resources/app/src/pane.js:658:20)
  at Pane.module.exports.Model.destroy (/usr/share/atom/resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroy (/usr/share/atom/resources/app/src/pane.js:649:39)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:413:21)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:457:16)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:179:22)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
I'm having some trouble reproducing this. Can anyone else reproduce. Does this happen when you run `atom --safe`?

**Comment by izuzak** [comment]
@toloco Are you still seeing this problem? I'm having trouble reproducing this as well, on Atom 0.192.0.

**Comment by toloco** [comment]
Sorry guys, it is on my working environment, let me check it tomorrow.

**Comment by izuzak** [comment]
Friendly ping, @toloco -- were you able to reproduce this problem on your other environment in Atom 0.198.0?

**Comment by toloco** [comment]
It's version 0.187.0

**Comment by thomasjo** [comment]
@toloco Please upgrade to the latest version of Atom (currently v0.198.0).
