### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by deserat** [atom/markdown-preview#243]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.131.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:118

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/vance.dubberly/.atom/packages/markdown-preview/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/vance.dubberly/.atom/packages/markdown-preview/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/vance.dubberly/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:8:10)
  at Object.<anonymous> (/Users/vance.dubberly/.atom/packages/markdown-preview/lib/markdown-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at isMarkdownPreviewView (/Users/vance.dubberly/.atom/packages/markdown-preview/lib/main.coffee:13:26)
  at Object.module.exports.toggle (/Users/vance.dubberly/.atom/packages/markdown-preview/lib/main.coffee:76:8)
  at atom-workspace.atom.commands.add.markdown-preview:toggle (/Users/vance.dubberly/.atom/packages/markdown-preview/lib/main.coffee:42:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
 11x -0:26.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:23.6 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:23.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:22.8 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:22.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 14x -0:21.8 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 10x -0:20.1 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:18.2 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:17.7 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 11x -0:17.5 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -0:15.1 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:13.4 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:13.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:09.6 editor:log-cursor-scope (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:07.2 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:00.5 markdown-preview:toggle (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
linter, v0.12.0
linter-pep8, v0.1.0
markdown-preview, v0.131.0
minimap, v4.5.0
vim-mode, v0.34.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
It looks like you're running an old user-installed version of markdown-preview - please uninstall it so it doesn't conflict with the version that ships with Atom 0.190.0 (e.g. in Settings or by running `apm uninstall markdown-preview`). Let me know if you have any questions!

**Comment by kevinsawicki** [comment]
@deserat If you delete the `/Users/vance.dubberly/.atom/packages/markdown-preview` folder and restart Atom, the issue should go away, this package is bundled with Atom and should not be installed to `/Users/vance.dubberly/.atom/packages`
