### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by iamale** [atom/markdown-preview#252]
Occurs when closing the preview tab.

**Atom Version**: 0.188.0
**System**: linux 3.11.0-12-generic
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.144.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of null

```
At /usr/share/atom/resources/app/node_modules/emissary/lib/subscriber.js:84

TypeError: Cannot read property 'indexOf' of null
  at Pane.module.exports.Subscriber.unsubscribe (/usr/share/atom/resources/app/node_modules/emissary/lib/subscriber.js:84:38)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app/src/pane.js:400:14)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app/src/pane.js:473:16)
  at Object.module.exports.removePreviewForEditor (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/main.js:136:21)
  at Object.module.exports.toggle (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/main.js:124:17)
  at atom-workspace.atom.commands.add.markdown-preview:toggle (/usr/share/atom/resources/app/node_modules/markdown-preview/lib/main.js:58:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:242:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
  6x -0:51.6 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:48.1 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:47.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.3 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:32.9 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -0:31.9 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -0:30.9 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:30.1 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:29.4 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:28.4 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:27.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.4 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:16.5 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.9 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.8 core:confirm (atom-text-editor.editor.mini)
  3x -0:10.8 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "neutron-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.0
gist-it, v0.6.10
language-pascal, v0.7.0
neutron-syntax, v0.6.2
term, v0.2.2
typewriter, v0.3.3

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
You're running a pretty old version of Atom – please update to the latest version (Atom 0.200.0).
