### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by 5T41N** [atom/markdown-preview#270]
[Enter steps to reproduce below:]

1. Open .md file from Spotlight
2. Select "Markdown Preview: Copy HTML" from command palette

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.150.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:449

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:449:13)
  at resolveImagePaths (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/renderer.js:118:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/renderer.js:78:14
  at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/roaster/lib/roaster.js:66:14)
  at render (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/renderer.js:73:12)
  at Object.exports.toHTML (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/renderer.js:50:12)
  at Object.module.exports.copyHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/main.js:193:23)
  at atom-workspace.atom.commands.add.markdown-preview:copy-html (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/markdown-preview/lib/main.js:68:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -0:13 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -0:07.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 markdown-preview:copy-html (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
jshint, v1.3.8
linter, v1.1.0
linter-csslint, v0.0.14
linter-htmlhint, v0.0.17
linter-php, v0.0.15
linter-pylint, v0.2.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Is there any chance you can share the contents of the Markdown file?

**Comment by 5T41N** [comment]
It does *not* happen consistently.
Here's the content:

```
# Chat
| ID          | PART                     | POSITION  |
|:-----------:|:------------------------:|:---------:|
| rand.hex(8) | string                   | int (1-3) |
| 1b32c2os    | eENYHYbQyVqW5FiOc+X85M/b | 3         |
```

# Chat
| ID          | PART                     | POSITION  |
|:-----------:|:------------------------:|:---------:|
| rand.hex(8) | string                   | int (1-3) |
| 1b32c2os    | eENYHYbQyVqW5FiOc+X85M/b | 3         |
