### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by rafaljanicki** [atom/markdown-preview#389]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-preview](https://github.com/atom/markdown-preview) package, v0.158.0

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\src\item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\src\item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\src\pane-container.js:387:25)
    at C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\src\pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\src\pane.js:485:20)
    at Pane.module.exports.Pane.activateItem (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\src\pane.js:428:14)
    at C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\markdown-preview\lib\markdown-preview-view.js:190:25
    at C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\markdown-preview\lib\markdown-preview-view.js:199:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\Dev\AppData\Local\atom\app-1.7.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1369:25
```

### Commands

```
     -2:50.6.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -2:46.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:28.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:20.3.0 core:move-to-top (atom-text-editor.editor.is-focused)
  3x -1:02.9.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:55.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:18 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.1.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:15.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  8x -0:11 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:10.1.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:09.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:03.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.4
language-plantuml, v0.2.0
line-ending-converter, v1.3.2
markdown-themeable-pdf, v1.0.1
pdf-view, v0.50.0
project-plus, v0.8.2

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
What were you doing when this error occurred?

**Comment by rafaljanicki** [comment]
Sorry for that, I haven't noticed the steps section.

Anyway, I wasn't doing anything extraordinary, just modifying a Markdown file
